### PR TITLE
shake build

### PR DESCRIPTION
**Pull request by epsilonhalbe**
Hey gonimaster,

here is the future (haskell-shake) build branch for gonimo-front.

Btw it seems i am still on vietnam time - thought i was not that much jet-lagged ;-)

### CODE REVIEW

**Comment by eskimor** [comment]
Nice! Although I would put this stuff in a separate repo, because we will need it also for the landingpage, so having a separate gonimo-build repo with executables for building front and the landing page might make sense.

**Comment by epsilonhalbe** [comment]
In my opinion it does not make sense to use the same build tool for the app and the landing page, as the one is using a complete different workflow (purescript and index.html template vs. PHP) therefore I will provide anther build tool for the landing page, which shares the same ideas

**Comment by eskimor** [comment]
Still not asleep? Well the link fixer is completely identical! So at least this part should be in it's own repo - no? But anyhow - let's get this ready in this sprint for the app, let's check out the landing page in the next sprint.

**Comment by epsilonhalbe** [comment]
finisheeeeed

**Pull request merged**
